CC = gcc
CFLAGS = -O2

mk_bwts: mk_bwts_sa.o map_file.o map_file.h
	$(CC) -o $@ mk_bwts_sa.o map_file.o win32/libdivsufsort.a

map_file.o: map_file.c map_file.h

mk_bwts_sa.o: mk_bwts_sa.c map_file.h divsufsort.h
	$(CC) -o $@ -c -include divsufsort.h $(CFLAGS) mk_bwts_sa.c

install: mk_bwts
	cp mk_bwts $(HOME)/bin/

clean:
	$(RM) *.o mk_bwts
